### ISSUE TITLE
Remove useless steps on main workflow

### ISSUE THREAD

**Issue by apomalyn** [apomalyn/kana_to_kanji#9]
Remove from the `main-workflow.yaml` the following lines:

```yaml
- name: Download iOS build
  uses: actions/download-artifact@v3
  with:
    name: iOS
- name: Download Android build
  uses: actions/download-artifact@v3
  with:
    name: Android
```

As they aren't needed anymore. The next step download all the artifacts into a folder
